/*
 * Public API
 * Assessment API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: helpdesk@codeinspect.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.fraunhofer.sit.sse.vusc.javaclient.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import de.fraunhofer.sit.sse.vusc.javaclient.models.AndroidPermission;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * APKMetadataAllOf
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-01-14T02:27:21.666995377Z[GMT]")
public class APKMetadataAllOf {
  public static final String SERIALIZED_NAME_PACKAGE_NAME = "packageName";
  @SerializedName(SERIALIZED_NAME_PACKAGE_NAME)
  private String packageName;

  public static final String SERIALIZED_NAME_MIN_S_D_K_VERSION = "minSDKVersion";
  @SerializedName(SERIALIZED_NAME_MIN_S_D_K_VERSION)
  private Integer minSDKVersion;

  public static final String SERIALIZED_NAME_TARGET_S_D_K_VERSION = "targetSDKVersion";
  @SerializedName(SERIALIZED_NAME_TARGET_S_D_K_VERSION)
  private Integer targetSDKVersion;

  public static final String SERIALIZED_NAME_PERMISSIONS = "permissions";
  @SerializedName(SERIALIZED_NAME_PERMISSIONS)
  private List<AndroidPermission> permissions = null;

  public APKMetadataAllOf() { 
  }

  public APKMetadataAllOf packageName(String packageName) {
    
    this.packageName = packageName;
    return this;
  }

   /**
   * The APK&#39;s package name
   * @return packageName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "com.examplecompany.app", value = "The APK's package name")

  public String getPackageName() {
    return packageName;
  }


  public void setPackageName(String packageName) {
    this.packageName = packageName;
  }


  public APKMetadataAllOf minSDKVersion(Integer minSDKVersion) {
    
    this.minSDKVersion = minSDKVersion;
    return this;
  }

   /**
   * The minimum Android SDK version needed to install this APK, as specified in the manifest
   * @return minSDKVersion
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "19", value = "The minimum Android SDK version needed to install this APK, as specified in the manifest")

  public Integer getMinSDKVersion() {
    return minSDKVersion;
  }


  public void setMinSDKVersion(Integer minSDKVersion) {
    this.minSDKVersion = minSDKVersion;
  }


  public APKMetadataAllOf targetSDKVersion(Integer targetSDKVersion) {
    
    this.targetSDKVersion = targetSDKVersion;
    return this;
  }

   /**
   * The Android SDK this APK was compiled against, as specified in the manifest
   * @return targetSDKVersion
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "25", value = "The Android SDK this APK was compiled against, as specified in the manifest")

  public Integer getTargetSDKVersion() {
    return targetSDKVersion;
  }


  public void setTargetSDKVersion(Integer targetSDKVersion) {
    this.targetSDKVersion = targetSDKVersion;
  }


  public APKMetadataAllOf permissions(List<AndroidPermission> permissions) {
    
    this.permissions = permissions;
    return this;
  }

  public APKMetadataAllOf addPermissionsItem(AndroidPermission permissionsItem) {
    if (this.permissions == null) {
      this.permissions = new ArrayList<AndroidPermission>();
    }
    this.permissions.add(permissionsItem);
    return this;
  }

   /**
   * The permissions the app uses, as specified in the manifest
   * @return permissions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "{ \"android.permission.CAMERA\" }", value = "The permissions the app uses, as specified in the manifest")

  public List<AndroidPermission> getPermissions() {
    return permissions;
  }


  public void setPermissions(List<AndroidPermission> permissions) {
    this.permissions = permissions;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    APKMetadataAllOf apKMetadataAllOf = (APKMetadataAllOf) o;
    return Objects.equals(this.packageName, apKMetadataAllOf.packageName) &&
        Objects.equals(this.minSDKVersion, apKMetadataAllOf.minSDKVersion) &&
        Objects.equals(this.targetSDKVersion, apKMetadataAllOf.targetSDKVersion) &&
        Objects.equals(this.permissions, apKMetadataAllOf.permissions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(packageName, minSDKVersion, targetSDKVersion, permissions);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class APKMetadataAllOf {\n");
    sb.append("    packageName: ").append(toIndentedString(packageName)).append("\n");
    sb.append("    minSDKVersion: ").append(toIndentedString(minSDKVersion)).append("\n");
    sb.append("    targetSDKVersion: ").append(toIndentedString(targetSDKVersion)).append("\n");
    sb.append("    permissions: ").append(toIndentedString(permissions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

