/*
 * Public API
 * Assessment API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: helpdesk@codeinspect.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.fraunhofer.sit.sse.vusc.javaclient.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import de.fraunhofer.sit.sse.vusc.javaclient.models.AdditionalData;
import de.fraunhofer.sit.sse.vusc.javaclient.models.Dataflow;
import de.fraunhofer.sit.sse.vusc.javaclient.models.Location;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Concrete instances where this communication is used
 */
@ApiModel(description = "Concrete instances where this communication is used")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-01-14T02:27:21.666995377Z[GMT]")
public class CommunicationInstance {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Long id;

  public static final String SERIALIZED_NAME_DATAFLOWS = "dataflows";
  @SerializedName(SERIALIZED_NAME_DATAFLOWS)
  private List<Dataflow> dataflows = null;

  public static final String SERIALIZED_NAME_ADDITIONAL_DATA = "additionalData";
  @SerializedName(SERIALIZED_NAME_ADDITIONAL_DATA)
  private List<AdditionalData> additionalData = null;

  public static final String SERIALIZED_NAME_CODE_LOCATION = "codeLocation";
  @SerializedName(SERIALIZED_NAME_CODE_LOCATION)
  private Location codeLocation;

  public static final String SERIALIZED_NAME_IS_POTENTIALLY_MALICIOUS = "isPotentiallyMalicious";
  @SerializedName(SERIALIZED_NAME_IS_POTENTIALLY_MALICIOUS)
  private Boolean isPotentiallyMalicious;

  public static final String SERIALIZED_NAME_PROTOCOL = "protocol";
  @SerializedName(SERIALIZED_NAME_PROTOCOL)
  private String protocol;

  public static final String SERIALIZED_NAME_PORT = "port";
  @SerializedName(SERIALIZED_NAME_PORT)
  private Integer port;

  public static final String SERIALIZED_NAME_PATH = "path";
  @SerializedName(SERIALIZED_NAME_PATH)
  private String path;

  public static final String SERIALIZED_NAME_FRAGMENT = "fragment";
  @SerializedName(SERIALIZED_NAME_FRAGMENT)
  private String fragment;

  public static final String SERIALIZED_NAME_QUERY = "query";
  @SerializedName(SERIALIZED_NAME_QUERY)
  private String query;

  public static final String SERIALIZED_NAME_USER_INFO = "userInfo";
  @SerializedName(SERIALIZED_NAME_USER_INFO)
  private String userInfo;

  public CommunicationInstance() { 
  }

  public CommunicationInstance id(Long id) {
    
    this.id = id;
    return this;
  }

   /**
   * The id
   * @return id
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The id")

  public Long getId() {
    return id;
  }


  public void setId(Long id) {
    this.id = id;
  }


  public CommunicationInstance dataflows(List<Dataflow> dataflows) {
    
    this.dataflows = dataflows;
    return this;
  }

  public CommunicationInstance addDataflowsItem(Dataflow dataflowsItem) {
    if (this.dataflows == null) {
      this.dataflows = new ArrayList<Dataflow>();
    }
    this.dataflows.add(dataflowsItem);
    return this;
  }

   /**
   * A list of dataflows relevant to this communication
   * @return dataflows
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A list of dataflows relevant to this communication")

  public List<Dataflow> getDataflows() {
    return dataflows;
  }


  public void setDataflows(List<Dataflow> dataflows) {
    this.dataflows = dataflows;
  }


  public CommunicationInstance additionalData(List<AdditionalData> additionalData) {
    
    this.additionalData = additionalData;
    return this;
  }

  public CommunicationInstance addAdditionalDataItem(AdditionalData additionalDataItem) {
    if (this.additionalData == null) {
      this.additionalData = new ArrayList<AdditionalData>();
    }
    this.additionalData.add(additionalDataItem);
    return this;
  }

   /**
   * A list of description-value data pairs relevant to this finding
   * @return additionalData
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A list of description-value data pairs relevant to this finding")

  public List<AdditionalData> getAdditionalData() {
    return additionalData;
  }


  public void setAdditionalData(List<AdditionalData> additionalData) {
    this.additionalData = additionalData;
  }


  public CommunicationInstance codeLocation(Location codeLocation) {
    
    this.codeLocation = codeLocation;
    return this;
  }

   /**
   * Get codeLocation
   * @return codeLocation
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Location getCodeLocation() {
    return codeLocation;
  }


  public void setCodeLocation(Location codeLocation) {
    this.codeLocation = codeLocation;
  }


  public CommunicationInstance isPotentiallyMalicious(Boolean isPotentiallyMalicious) {
    
    this.isPotentiallyMalicious = isPotentiallyMalicious;
    return this;
  }

   /**
   * True if the url is known to serve dangerous content e.g. malware. If the value is false does not guarantee that the domain is safe.
   * @return isPotentiallyMalicious
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "True if the url is known to serve dangerous content e.g. malware. If the value is false does not guarantee that the domain is safe.")

  public Boolean getIsPotentiallyMalicious() {
    return isPotentiallyMalicious;
  }


  public void setIsPotentiallyMalicious(Boolean isPotentiallyMalicious) {
    this.isPotentiallyMalicious = isPotentiallyMalicious;
  }


  public CommunicationInstance protocol(String protocol) {
    
    this.protocol = protocol;
    return this;
  }

   /**
   * The protocol used to communicate with the remote host
   * @return protocol
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "http", value = "The protocol used to communicate with the remote host")

  public String getProtocol() {
    return protocol;
  }


  public void setProtocol(String protocol) {
    this.protocol = protocol;
  }


  public CommunicationInstance port(Integer port) {
    
    this.port = port;
    return this;
  }

   /**
   * The port used to communicate with the remote host
   * @return port
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "80", value = "The port used to communicate with the remote host")

  public Integer getPort() {
    return port;
  }


  public void setPort(Integer port) {
    this.port = port;
  }


  public CommunicationInstance path(String path) {
    
    this.path = path;
    return this;
  }

   /**
   * The path
   * @return path
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "/foo/bar", value = "The path")

  public String getPath() {
    return path;
  }


  public void setPath(String path) {
    this.path = path;
  }


  public CommunicationInstance fragment(String fragment) {
    
    this.fragment = fragment;
    return this;
  }

   /**
   * The fragment/anchor of the URI/URL (part after the #)
   * @return fragment
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "headline1", value = "The fragment/anchor of the URI/URL (part after the #)")

  public String getFragment() {
    return fragment;
  }


  public void setFragment(String fragment) {
    this.fragment = fragment;
  }


  public CommunicationInstance query(String query) {
    
    this.query = query;
    return this;
  }

   /**
   * The part after the ?, which may contain GET parameter values
   * @return query
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "name=Adam&age=20", value = "The part after the ?, which may contain GET parameter values")

  public String getQuery() {
    return query;
  }


  public void setQuery(String query) {
    this.query = query;
  }


  public CommunicationInstance userInfo(String userInfo) {
    
    this.userInfo = userInfo;
    return this;
  }

   /**
   * In an URI like http://user:password@example.com the user:password part
   * @return userInfo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "user:password", value = "In an URI like http://user:password@example.com the user:password part")

  public String getUserInfo() {
    return userInfo;
  }


  public void setUserInfo(String userInfo) {
    this.userInfo = userInfo;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CommunicationInstance communicationInstance = (CommunicationInstance) o;
    return Objects.equals(this.id, communicationInstance.id) &&
        Objects.equals(this.dataflows, communicationInstance.dataflows) &&
        Objects.equals(this.additionalData, communicationInstance.additionalData) &&
        Objects.equals(this.codeLocation, communicationInstance.codeLocation) &&
        Objects.equals(this.isPotentiallyMalicious, communicationInstance.isPotentiallyMalicious) &&
        Objects.equals(this.protocol, communicationInstance.protocol) &&
        Objects.equals(this.port, communicationInstance.port) &&
        Objects.equals(this.path, communicationInstance.path) &&
        Objects.equals(this.fragment, communicationInstance.fragment) &&
        Objects.equals(this.query, communicationInstance.query) &&
        Objects.equals(this.userInfo, communicationInstance.userInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, dataflows, additionalData, codeLocation, isPotentiallyMalicious, protocol, port, path, fragment, query, userInfo);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CommunicationInstance {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    dataflows: ").append(toIndentedString(dataflows)).append("\n");
    sb.append("    additionalData: ").append(toIndentedString(additionalData)).append("\n");
    sb.append("    codeLocation: ").append(toIndentedString(codeLocation)).append("\n");
    sb.append("    isPotentiallyMalicious: ").append(toIndentedString(isPotentiallyMalicious)).append("\n");
    sb.append("    protocol: ").append(toIndentedString(protocol)).append("\n");
    sb.append("    port: ").append(toIndentedString(port)).append("\n");
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("    fragment: ").append(toIndentedString(fragment)).append("\n");
    sb.append("    query: ").append(toIndentedString(query)).append("\n");
    sb.append("    userInfo: ").append(toIndentedString(userInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

