/*
 * Public API
 * Assessment API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: helpdesk@codeinspect.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.fraunhofer.sit.sse.vusc.javaclient.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import de.fraunhofer.sit.sse.vusc.javaclient.models.CommunicationInstance;
import de.fraunhofer.sit.sse.vusc.javaclient.models.GeoLocation;
import de.fraunhofer.sit.sse.vusc.javaclient.models.HostTLSConfiguration;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

/**
 * An abstraction of a communication
 */
@ApiModel(description = "An abstraction of a communication")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-01-14T02:27:21.666995377Z[GMT]")
public class Communication {
  public static final String SERIALIZED_NAME_HOST = "host";
  @SerializedName(SERIALIZED_NAME_HOST)
  private String host;

  public static final String SERIALIZED_NAME_SERVER_CONFIGURATION = "serverConfiguration";
  @SerializedName(SERIALIZED_NAME_SERVER_CONFIGURATION)
  private HostTLSConfiguration serverConfiguration;

  public static final String SERIALIZED_NAME_POSSIBLE_LOCATION = "possibleLocation";
  @SerializedName(SERIALIZED_NAME_POSSIBLE_LOCATION)
  private GeoLocation possibleLocation;

  public static final String SERIALIZED_NAME_INSTANCES = "instances";
  @SerializedName(SERIALIZED_NAME_INSTANCES)
  private Set<CommunicationInstance> instances = null;

  public static final String SERIALIZED_NAME_IP_ADDRESS = "ipAddress";
  @SerializedName(SERIALIZED_NAME_IP_ADDRESS)
  private String ipAddress;

  public Communication() { 
  }

  public Communication host(String host) {
    
    this.host = host;
    return this;
  }

   /**
   * The host this communication uses
   * @return host
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "www.website.com", value = "The host this communication uses")

  public String getHost() {
    return host;
  }


  public void setHost(String host) {
    this.host = host;
  }


  public Communication serverConfiguration(HostTLSConfiguration serverConfiguration) {
    
    this.serverConfiguration = serverConfiguration;
    return this;
  }

   /**
   * Get serverConfiguration
   * @return serverConfiguration
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public HostTLSConfiguration getServerConfiguration() {
    return serverConfiguration;
  }


  public void setServerConfiguration(HostTLSConfiguration serverConfiguration) {
    this.serverConfiguration = serverConfiguration;
  }


  public Communication possibleLocation(GeoLocation possibleLocation) {
    
    this.possibleLocation = possibleLocation;
    return this;
  }

   /**
   * Get possibleLocation
   * @return possibleLocation
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public GeoLocation getPossibleLocation() {
    return possibleLocation;
  }


  public void setPossibleLocation(GeoLocation possibleLocation) {
    this.possibleLocation = possibleLocation;
  }


  public Communication instances(Set<CommunicationInstance> instances) {
    
    this.instances = instances;
    return this;
  }

  public Communication addInstancesItem(CommunicationInstance instancesItem) {
    if (this.instances == null) {
      this.instances = new LinkedHashSet<CommunicationInstance>();
    }
    this.instances.add(instancesItem);
    return this;
  }

   /**
   * Concrete instances where this communication is used
   * @return instances
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Concrete instances where this communication is used")

  public Set<CommunicationInstance> getInstances() {
    return instances;
  }


  public void setInstances(Set<CommunicationInstance> instances) {
    this.instances = instances;
  }


  public Communication ipAddress(String ipAddress) {
    
    this.ipAddress = ipAddress;
    return this;
  }

   /**
   * The ip address of the remote host
   * @return ipAddress
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "127.0.0.1", value = "The ip address of the remote host")

  public String getIpAddress() {
    return ipAddress;
  }


  public void setIpAddress(String ipAddress) {
    this.ipAddress = ipAddress;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Communication communication = (Communication) o;
    return Objects.equals(this.host, communication.host) &&
        Objects.equals(this.serverConfiguration, communication.serverConfiguration) &&
        Objects.equals(this.possibleLocation, communication.possibleLocation) &&
        Objects.equals(this.instances, communication.instances) &&
        Objects.equals(this.ipAddress, communication.ipAddress);
  }

  @Override
  public int hashCode() {
    return Objects.hash(host, serverConfiguration, possibleLocation, instances, ipAddress);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Communication {\n");
    sb.append("    host: ").append(toIndentedString(host)).append("\n");
    sb.append("    serverConfiguration: ").append(toIndentedString(serverConfiguration)).append("\n");
    sb.append("    possibleLocation: ").append(toIndentedString(possibleLocation)).append("\n");
    sb.append("    instances: ").append(toIndentedString(instances)).append("\n");
    sb.append("    ipAddress: ").append(toIndentedString(ipAddress)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

