/*
 * Public API
 * Assessment API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: helpdesk@codeinspect.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.fraunhofer.sit.sse.vusc.javaclient.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import de.fraunhofer.sit.sse.vusc.javaclient.models.FindingStatistics;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Detailed status information
 */
@ApiModel(description = "Detailed status information")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-01-14T02:27:21.666995377Z[GMT]")
public class DetailedJobStatus {
  public static final String SERIALIZED_NAME_PENDING_ANALYSES = "pendingAnalyses";
  @SerializedName(SERIALIZED_NAME_PENDING_ANALYSES)
  private Integer pendingAnalyses;

  public static final String SERIALIZED_NAME_SKIPPED_ANALYSES = "skippedAnalyses";
  @SerializedName(SERIALIZED_NAME_SKIPPED_ANALYSES)
  private Integer skippedAnalyses;

  public static final String SERIALIZED_NAME_RUNNING_ANALYSES = "runningAnalyses";
  @SerializedName(SERIALIZED_NAME_RUNNING_ANALYSES)
  private Integer runningAnalyses;

  public static final String SERIALIZED_NAME_FAILED_ANALYSES = "failedAnalyses";
  @SerializedName(SERIALIZED_NAME_FAILED_ANALYSES)
  private Integer failedAnalyses;

  public static final String SERIALIZED_NAME_FINISHED_ANALYSES = "finishedAnalyses";
  @SerializedName(SERIALIZED_NAME_FINISHED_ANALYSES)
  private Integer finishedAnalyses;

  public static final String SERIALIZED_NAME_HAS_WARNINGS = "hasWarnings";
  @SerializedName(SERIALIZED_NAME_HAS_WARNINGS)
  private Boolean hasWarnings;

  public static final String SERIALIZED_NAME_STATUS_TEXT = "statusText";
  @SerializedName(SERIALIZED_NAME_STATUS_TEXT)
  private String statusText;

  public static final String SERIALIZED_NAME_VULNERABILITY_FINDING_STATISTICS = "vulnerabilityFindingStatistics";
  @SerializedName(SERIALIZED_NAME_VULNERABILITY_FINDING_STATISTICS)
  private FindingStatistics vulnerabilityFindingStatistics;

  public static final String SERIALIZED_NAME_PROGRESS_PERCENT = "progressPercent";
  @SerializedName(SERIALIZED_NAME_PROGRESS_PERCENT)
  private Integer progressPercent;

  public static final String SERIALIZED_NAME_FINISH_DATE = "finishDate";
  @SerializedName(SERIALIZED_NAME_FINISH_DATE)
  private Long finishDate;

  public DetailedJobStatus() { 
  }

  public DetailedJobStatus pendingAnalyses(Integer pendingAnalyses) {
    
    this.pendingAnalyses = pendingAnalyses;
    return this;
  }

   /**
   * The number of pending analyses
   * @return pendingAnalyses
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "3", required = true, value = "The number of pending analyses")

  public Integer getPendingAnalyses() {
    return pendingAnalyses;
  }


  public void setPendingAnalyses(Integer pendingAnalyses) {
    this.pendingAnalyses = pendingAnalyses;
  }


  public DetailedJobStatus skippedAnalyses(Integer skippedAnalyses) {
    
    this.skippedAnalyses = skippedAnalyses;
    return this;
  }

   /**
   * The number of skipped analyses
   * @return skippedAnalyses
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "0", required = true, value = "The number of skipped analyses")

  public Integer getSkippedAnalyses() {
    return skippedAnalyses;
  }


  public void setSkippedAnalyses(Integer skippedAnalyses) {
    this.skippedAnalyses = skippedAnalyses;
  }


  public DetailedJobStatus runningAnalyses(Integer runningAnalyses) {
    
    this.runningAnalyses = runningAnalyses;
    return this;
  }

   /**
   * The number of currently running analyses
   * @return runningAnalyses
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "2", required = true, value = "The number of currently running analyses")

  public Integer getRunningAnalyses() {
    return runningAnalyses;
  }


  public void setRunningAnalyses(Integer runningAnalyses) {
    this.runningAnalyses = runningAnalyses;
  }


  public DetailedJobStatus failedAnalyses(Integer failedAnalyses) {
    
    this.failedAnalyses = failedAnalyses;
    return this;
  }

   /**
   * The number of failed analyses
   * @return failedAnalyses
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "0", required = true, value = "The number of failed analyses")

  public Integer getFailedAnalyses() {
    return failedAnalyses;
  }


  public void setFailedAnalyses(Integer failedAnalyses) {
    this.failedAnalyses = failedAnalyses;
  }


  public DetailedJobStatus finishedAnalyses(Integer finishedAnalyses) {
    
    this.finishedAnalyses = finishedAnalyses;
    return this;
  }

   /**
   * The number of finished analyses
   * @return finishedAnalyses
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "52", required = true, value = "The number of finished analyses")

  public Integer getFinishedAnalyses() {
    return finishedAnalyses;
  }


  public void setFinishedAnalyses(Integer finishedAnalyses) {
    this.finishedAnalyses = finishedAnalyses;
  }


  public DetailedJobStatus hasWarnings(Boolean hasWarnings) {
    
    this.hasWarnings = hasWarnings;
    return this;
  }

   /**
   * Whether the job has had some warnings during analysis
   * @return hasWarnings
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Whether the job has had some warnings during analysis")

  public Boolean getHasWarnings() {
    return hasWarnings;
  }


  public void setHasWarnings(Boolean hasWarnings) {
    this.hasWarnings = hasWarnings;
  }


  public DetailedJobStatus statusText(String statusText) {
    
    this.statusText = statusText;
    return this;
  }

   /**
   * Get statusText
   * @return statusText
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getStatusText() {
    return statusText;
  }


  public void setStatusText(String statusText) {
    this.statusText = statusText;
  }


  public DetailedJobStatus vulnerabilityFindingStatistics(FindingStatistics vulnerabilityFindingStatistics) {
    
    this.vulnerabilityFindingStatistics = vulnerabilityFindingStatistics;
    return this;
  }

   /**
   * Get vulnerabilityFindingStatistics
   * @return vulnerabilityFindingStatistics
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public FindingStatistics getVulnerabilityFindingStatistics() {
    return vulnerabilityFindingStatistics;
  }


  public void setVulnerabilityFindingStatistics(FindingStatistics vulnerabilityFindingStatistics) {
    this.vulnerabilityFindingStatistics = vulnerabilityFindingStatistics;
  }


  public DetailedJobStatus progressPercent(Integer progressPercent) {
    
    this.progressPercent = progressPercent;
    return this;
  }

   /**
   * A progress estimation in percent
   * @return progressPercent
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "91", required = true, value = "A progress estimation in percent")

  public Integer getProgressPercent() {
    return progressPercent;
  }


  public void setProgressPercent(Integer progressPercent) {
    this.progressPercent = progressPercent;
  }


  public DetailedJobStatus finishDate(Long finishDate) {
    
    this.finishDate = finishDate;
    return this;
  }

   /**
   * The time this job finished, or -1 if it has not finished yet
   * @return finishDate
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "12829842123", required = true, value = "The time this job finished, or -1 if it has not finished yet")

  public Long getFinishDate() {
    return finishDate;
  }


  public void setFinishDate(Long finishDate) {
    this.finishDate = finishDate;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DetailedJobStatus detailedJobStatus = (DetailedJobStatus) o;
    return Objects.equals(this.pendingAnalyses, detailedJobStatus.pendingAnalyses) &&
        Objects.equals(this.skippedAnalyses, detailedJobStatus.skippedAnalyses) &&
        Objects.equals(this.runningAnalyses, detailedJobStatus.runningAnalyses) &&
        Objects.equals(this.failedAnalyses, detailedJobStatus.failedAnalyses) &&
        Objects.equals(this.finishedAnalyses, detailedJobStatus.finishedAnalyses) &&
        Objects.equals(this.hasWarnings, detailedJobStatus.hasWarnings) &&
        Objects.equals(this.statusText, detailedJobStatus.statusText) &&
        Objects.equals(this.vulnerabilityFindingStatistics, detailedJobStatus.vulnerabilityFindingStatistics) &&
        Objects.equals(this.progressPercent, detailedJobStatus.progressPercent) &&
        Objects.equals(this.finishDate, detailedJobStatus.finishDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pendingAnalyses, skippedAnalyses, runningAnalyses, failedAnalyses, finishedAnalyses, hasWarnings, statusText, vulnerabilityFindingStatistics, progressPercent, finishDate);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DetailedJobStatus {\n");
    sb.append("    pendingAnalyses: ").append(toIndentedString(pendingAnalyses)).append("\n");
    sb.append("    skippedAnalyses: ").append(toIndentedString(skippedAnalyses)).append("\n");
    sb.append("    runningAnalyses: ").append(toIndentedString(runningAnalyses)).append("\n");
    sb.append("    failedAnalyses: ").append(toIndentedString(failedAnalyses)).append("\n");
    sb.append("    finishedAnalyses: ").append(toIndentedString(finishedAnalyses)).append("\n");
    sb.append("    hasWarnings: ").append(toIndentedString(hasWarnings)).append("\n");
    sb.append("    statusText: ").append(toIndentedString(statusText)).append("\n");
    sb.append("    vulnerabilityFindingStatistics: ").append(toIndentedString(vulnerabilityFindingStatistics)).append("\n");
    sb.append("    progressPercent: ").append(toIndentedString(progressPercent)).append("\n");
    sb.append("    finishDate: ").append(toIndentedString(finishDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

