/*
 * Public API
 * Assessment API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: helpdesk@codeinspect.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.fraunhofer.sit.sse.vusc.javaclient.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import de.fraunhofer.sit.sse.vusc.javaclient.models.CatalogReference;
import de.fraunhofer.sit.sse.vusc.javaclient.models.ReferenceGroup;
import de.fraunhofer.sit.sse.vusc.javaclient.models.URLExternalReference;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * A reference to an external resource
 */
@ApiModel(description = "A reference to an external resource")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-01-14T02:27:21.666995377Z[GMT]")
public class ExternalReference {
  public static final String SERIALIZED_NAME_SHORT_DESCRIPTION = "shortDescription";
  @SerializedName(SERIALIZED_NAME_SHORT_DESCRIPTION)
  private String shortDescription;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  protected String type;

  public static final String SERIALIZED_NAME_REFERENCE_GROUP = "referenceGroup";
  @SerializedName(SERIALIZED_NAME_REFERENCE_GROUP)
  private ReferenceGroup referenceGroup;

  public ExternalReference() { 
    this.type = this.getClass().getSimpleName();
  }

  public ExternalReference shortDescription(String shortDescription) {
    
    this.shortDescription = shortDescription;
    return this;
  }

   /**
   * A short description of the content
   * @return shortDescription
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "The Android developer documentation", required = true, value = "A short description of the content")

  public String getShortDescription() {
    return shortDescription;
  }


  public void setShortDescription(String shortDescription) {
    this.shortDescription = shortDescription;
  }


  public ExternalReference type(String type) {
    
    this.type = type;
    return this;
  }

   /**
   * The type of reference
   * @return type
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "URLExternalReference", required = true, value = "The type of reference")

  public String getType() {
    return type;
  }


  public void setType(String type) {
    this.type = type;
  }


  public ExternalReference referenceGroup(ReferenceGroup referenceGroup) {
    
    this.referenceGroup = referenceGroup;
    return this;
  }

   /**
   * Get referenceGroup
   * @return referenceGroup
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public ReferenceGroup getReferenceGroup() {
    return referenceGroup;
  }


  public void setReferenceGroup(ReferenceGroup referenceGroup) {
    this.referenceGroup = referenceGroup;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExternalReference externalReference = (ExternalReference) o;
    return Objects.equals(this.shortDescription, externalReference.shortDescription) &&
        Objects.equals(this.type, externalReference.type) &&
        Objects.equals(this.referenceGroup, externalReference.referenceGroup);
  }

  @Override
  public int hashCode() {
    return Objects.hash(shortDescription, type, referenceGroup);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExternalReference {\n");
    sb.append("    shortDescription: ").append(toIndentedString(shortDescription)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    referenceGroup: ").append(toIndentedString(referenceGroup)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

