/*
 * Public API
 * Assessment API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: helpdesk@codeinspect.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.fraunhofer.sit.sse.vusc.javaclient.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import de.fraunhofer.sit.sse.vusc.javaclient.models.BinaryCodeLocation;
import de.fraunhofer.sit.sse.vusc.javaclient.models.CodeLocation;
import de.fraunhofer.sit.sse.vusc.javaclient.models.FileLocation;
import de.fraunhofer.sit.sse.vusc.javaclient.models.FileLocationAllOf;
import de.fraunhofer.sit.sse.vusc.javaclient.models.Location;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * The position of a string of text in a specific file
 */
@ApiModel(description = "The position of a string of text in a specific file")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-01-14T02:27:21.666995377Z[GMT]")
public class FileLocation extends Location {
  public static final String SERIALIZED_NAME_FILE_PATH = "filePath";
  @SerializedName(SERIALIZED_NAME_FILE_PATH)
  private String filePath;

  public static final String SERIALIZED_NAME_CHARACTER_START = "characterStart";
  @SerializedName(SERIALIZED_NAME_CHARACTER_START)
  private Integer characterStart;

  public static final String SERIALIZED_NAME_CHARACTER_LENGTH = "characterLength";
  @SerializedName(SERIALIZED_NAME_CHARACTER_LENGTH)
  private Integer characterLength;

  public FileLocation() { 
    this.type = this.getClass().getSimpleName();
  }

  public FileLocation filePath(String filePath) {
    
    this.filePath = filePath;
    return this;
  }

   /**
   * The file&#39;s path
   * @return filePath
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "AndroidManifest.xml", required = true, value = "The file's path")

  public String getFilePath() {
    return filePath;
  }


  public void setFilePath(String filePath) {
    this.filePath = filePath;
  }


  public FileLocation characterStart(Integer characterStart) {
    
    this.characterStart = characterStart;
    return this;
  }

   /**
   * The position of the first character of this string
   * @return characterStart
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "51", required = true, value = "The position of the first character of this string")

  public Integer getCharacterStart() {
    return characterStart;
  }


  public void setCharacterStart(Integer characterStart) {
    this.characterStart = characterStart;
  }


  public FileLocation characterLength(Integer characterLength) {
    
    this.characterLength = characterLength;
    return this;
  }

   /**
   * The length of the string
   * @return characterLength
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "10", required = true, value = "The length of the string")

  public Integer getCharacterLength() {
    return characterLength;
  }


  public void setCharacterLength(Integer characterLength) {
    this.characterLength = characterLength;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FileLocation fileLocation = (FileLocation) o;
    return Objects.equals(this.filePath, fileLocation.filePath) &&
        Objects.equals(this.characterStart, fileLocation.characterStart) &&
        Objects.equals(this.characterLength, fileLocation.characterLength) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(filePath, characterStart, characterLength, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FileLocation {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    filePath: ").append(toIndentedString(filePath)).append("\n");
    sb.append("    characterStart: ").append(toIndentedString(characterStart)).append("\n");
    sb.append("    characterLength: ").append(toIndentedString(characterLength)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

