/*
 * Public API
 * Assessment API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: helpdesk@codeinspect.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.fraunhofer.sit.sse.vusc.javaclient.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Information which was found in the analyzed application, but may expose private information about the build environment, the developers or internal infrastructures.
 */
@ApiModel(description = "Information which was found in the analyzed application, but may expose private information about the build environment, the developers or internal infrastructures.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-01-14T02:27:21.666995377Z[GMT]")
public class ResidualDataType {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_SHORT_DESCRIPTION = "shortDescription";
  @SerializedName(SERIALIZED_NAME_SHORT_DESCRIPTION)
  private String shortDescription;

  public ResidualDataType() { 
  }

  public ResidualDataType id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * What kind of data was found
   * @return id
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "COPYRIGHT", required = true, value = "What kind of data was found")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public ResidualDataType description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * A long description
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Geolocation data has been found in a file's EXIF metadata. This information could be sensitive to the developer and can be exploited in a social engineering attack.", value = "A long description")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public ResidualDataType shortDescription(String shortDescription) {
    
    this.shortDescription = shortDescription;
    return this;
  }

   /**
   * A short description
   * @return shortDescription
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Geolocation data", value = "A short description")

  public String getShortDescription() {
    return shortDescription;
  }


  public void setShortDescription(String shortDescription) {
    this.shortDescription = shortDescription;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResidualDataType residualDataType = (ResidualDataType) o;
    return Objects.equals(this.id, residualDataType.id) &&
        Objects.equals(this.description, residualDataType.description) &&
        Objects.equals(this.shortDescription, residualDataType.shortDescription);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, description, shortDescription);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResidualDataType {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    shortDescription: ").append(toIndentedString(shortDescription)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

