/*
 * Public API
 * Assessment API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: helpdesk@codeinspect.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.fraunhofer.sit.sse.vusc.javaclient.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import de.fraunhofer.sit.sse.vusc.javaclient.models.AdditionalData;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Additional optional meta data about a source or sink in a data flow
 */
@ApiModel(description = "Additional optional meta data about a source or sink in a data flow")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-01-14T02:27:21.666995377Z[GMT]")
public class SourceSinkMetaData {
  public static final String SERIALIZED_NAME_ADDITIONAL_INFO = "additionalInfo";
  @SerializedName(SERIALIZED_NAME_ADDITIONAL_INFO)
  private List<AdditionalData> additionalInfo = null;

  public SourceSinkMetaData() { 
  }

  public SourceSinkMetaData additionalInfo(List<AdditionalData> additionalInfo) {
    
    this.additionalInfo = additionalInfo;
    return this;
  }

  public SourceSinkMetaData addAdditionalInfoItem(AdditionalData additionalInfoItem) {
    if (this.additionalInfo == null) {
      this.additionalInfo = new ArrayList<AdditionalData>();
    }
    this.additionalInfo.add(additionalInfoItem);
    return this;
  }

   /**
   * Additional data about the source or sink, such as the name of the file into which the data is written.
   * @return additionalInfo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Additional data about the source or sink, such as the name of the file into which the data is written.")

  public List<AdditionalData> getAdditionalInfo() {
    return additionalInfo;
  }


  public void setAdditionalInfo(List<AdditionalData> additionalInfo) {
    this.additionalInfo = additionalInfo;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SourceSinkMetaData sourceSinkMetaData = (SourceSinkMetaData) o;
    return Objects.equals(this.additionalInfo, sourceSinkMetaData.additionalInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(additionalInfo);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SourceSinkMetaData {\n");
    sb.append("    additionalInfo: ").append(toIndentedString(additionalInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

