/*
 * Public API
 * Assessment API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: helpdesk@codeinspect.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.fraunhofer.sit.sse.vusc.javaclient.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;

/**
 * The used consumables
 */
@ApiModel(description = "The used consumables")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-01-14T02:27:21.666995377Z[GMT]")
public class UsedConsumable {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_DISPLAY_NAME = "displayName";
  @SerializedName(SERIALIZED_NAME_DISPLAY_NAME)
  private String displayName;

  public static final String SERIALIZED_NAME_CONSUMPTION_DATE = "consumptionDate";
  @SerializedName(SERIALIZED_NAME_CONSUMPTION_DATE)
  private OffsetDateTime consumptionDate;

  public UsedConsumable() { 
  }

  public UsedConsumable id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * The id
   * @return id
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The id")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public UsedConsumable displayName(String displayName) {
    
    this.displayName = displayName;
    return this;
  }

   /**
   * The display name
   * @return displayName
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The display name")

  public String getDisplayName() {
    return displayName;
  }


  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }


  public UsedConsumable consumptionDate(OffsetDateTime consumptionDate) {
    
    this.consumptionDate = consumptionDate;
    return this;
  }

   /**
   * The date of consumption
   * @return consumptionDate
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The date of consumption")

  public OffsetDateTime getConsumptionDate() {
    return consumptionDate;
  }


  public void setConsumptionDate(OffsetDateTime consumptionDate) {
    this.consumptionDate = consumptionDate;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UsedConsumable usedConsumable = (UsedConsumable) o;
    return Objects.equals(this.id, usedConsumable.id) &&
        Objects.equals(this.displayName, usedConsumable.displayName) &&
        Objects.equals(this.consumptionDate, usedConsumable.consumptionDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, displayName, consumptionDate);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UsedConsumable {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    consumptionDate: ").append(toIndentedString(consumptionDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

