/*
 * Public API
 * Assessment API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: helpdesk@codeinspect.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.fraunhofer.sit.sse.vusc.javaclient.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import de.fraunhofer.sit.sse.vusc.javaclient.models.APKMetadata;
import de.fraunhofer.sit.sse.vusc.javaclient.models.EARMetadata;
import de.fraunhofer.sit.sse.vusc.javaclient.models.ELFMetadata;
import de.fraunhofer.sit.sse.vusc.javaclient.models.IPAMetadata;
import de.fraunhofer.sit.sse.vusc.javaclient.models.JARProgramMetadata;
import de.fraunhofer.sit.sse.vusc.javaclient.models.JNLPMetadata;
import de.fraunhofer.sit.sse.vusc.javaclient.models.JobMetadata;
import de.fraunhofer.sit.sse.vusc.javaclient.models.Platform;
import de.fraunhofer.sit.sse.vusc.javaclient.models.SpringApplicationMetadata;
import de.fraunhofer.sit.sse.vusc.javaclient.models.UWPMetadata;
import de.fraunhofer.sit.sse.vusc.javaclient.models.UWPMetadataAllOf;
import de.fraunhofer.sit.sse.vusc.javaclient.models.WARMetadata;
import de.fraunhofer.sit.sse.vusc.javaclient.models.WindowsMetadata;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Metadata for a UWP app
 */
@ApiModel(description = "Metadata for a UWP app")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-01-14T02:27:21.666995377Z[GMT]")
public class UWPMetadata extends JobMetadata {
  public static final String SERIALIZED_NAME_PUBLISHER = "publisher";
  @SerializedName(SERIALIZED_NAME_PUBLISHER)
  private String publisher;

  public static final String SERIALIZED_NAME_MIN_VERSION = "minVersion";
  @SerializedName(SERIALIZED_NAME_MIN_VERSION)
  private String minVersion;

  public static final String SERIALIZED_NAME_MAX_VERSION_TESTED = "maxVersionTested";
  @SerializedName(SERIALIZED_NAME_MAX_VERSION_TESTED)
  private String maxVersionTested;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public UWPMetadata() { 
    this.type = this.getClass().getSimpleName();
  }

  public UWPMetadata publisher(String publisher) {
    
    this.publisher = publisher;
    return this;
  }

   /**
   * The specified publisher name
   * @return publisher
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Company Inc.", value = "The specified publisher name")

  public String getPublisher() {
    return publisher;
  }


  public void setPublisher(String publisher) {
    this.publisher = publisher;
  }


  public UWPMetadata minVersion(String minVersion) {
    
    this.minVersion = minVersion;
    return this;
  }

   /**
   * The specified minimum version of Windows
   * @return minVersion
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "10.0.0.0", value = "The specified minimum version of Windows")

  public String getMinVersion() {
    return minVersion;
  }


  public void setMinVersion(String minVersion) {
    this.minVersion = minVersion;
  }


  public UWPMetadata maxVersionTested(String maxVersionTested) {
    
    this.maxVersionTested = maxVersionTested;
    return this;
  }

   /**
   * The specified maximum version of Windows this app was tested with
   * @return maxVersionTested
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "10.0.16299.431", value = "The specified maximum version of Windows this app was tested with")

  public String getMaxVersionTested() {
    return maxVersionTested;
  }


  public void setMaxVersionTested(String maxVersionTested) {
    this.maxVersionTested = maxVersionTested;
  }


  public UWPMetadata description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * The specified description of this app
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "This is a UWP application", value = "The specified description of this app")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UWPMetadata uwPMetadata = (UWPMetadata) o;
    return Objects.equals(this.publisher, uwPMetadata.publisher) &&
        Objects.equals(this.minVersion, uwPMetadata.minVersion) &&
        Objects.equals(this.maxVersionTested, uwPMetadata.maxVersionTested) &&
        Objects.equals(this.description, uwPMetadata.description) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(publisher, minVersion, maxVersionTested, description, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UWPMetadata {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    publisher: ").append(toIndentedString(publisher)).append("\n");
    sb.append("    minVersion: ").append(toIndentedString(minVersion)).append("\n");
    sb.append("    maxVersionTested: ").append(toIndentedString(maxVersionTested)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

