/*
 * Public API
 * Assessment API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: helpdesk@codeinspect.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.fraunhofer.sit.sse.vusc.javaclient.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import de.fraunhofer.sit.sse.vusc.javaclient.models.APKMetadata;
import de.fraunhofer.sit.sse.vusc.javaclient.models.EARMetadata;
import de.fraunhofer.sit.sse.vusc.javaclient.models.ELFMetadata;
import de.fraunhofer.sit.sse.vusc.javaclient.models.IPAMetadata;
import de.fraunhofer.sit.sse.vusc.javaclient.models.JARProgramMetadata;
import de.fraunhofer.sit.sse.vusc.javaclient.models.JNLPMetadata;
import de.fraunhofer.sit.sse.vusc.javaclient.models.JobMetadata;
import de.fraunhofer.sit.sse.vusc.javaclient.models.Platform;
import de.fraunhofer.sit.sse.vusc.javaclient.models.SpringApplicationMetadata;
import de.fraunhofer.sit.sse.vusc.javaclient.models.UWPMetadata;
import de.fraunhofer.sit.sse.vusc.javaclient.models.WARMetadata;
import de.fraunhofer.sit.sse.vusc.javaclient.models.WARMetadataAllOf;
import de.fraunhofer.sit.sse.vusc.javaclient.models.WindowsMetadata;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Metadata for a Java Web Archive
 */
@ApiModel(description = "Metadata for a Java Web Archive")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-01-14T02:27:21.666995377Z[GMT]")
public class WARMetadata extends JobMetadata {
  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public WARMetadata() { 
    this.type = this.getClass().getSimpleName();
  }

  public WARMetadata description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * The specified description
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "My website", value = "The specified description")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WARMetadata waRMetadata = (WARMetadata) o;
    return Objects.equals(this.description, waRMetadata.description) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WARMetadata {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

