/*
 * Public API
 * Assessment API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: helpdesk@codeinspect.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.fraunhofer.sit.sse.vusc.javaclient.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * WindowsMetadataAllOf
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-01-14T02:27:21.666995377Z[GMT]")
public class WindowsMetadataAllOf {
  public static final String SERIALIZED_NAME_COMPANY_NAME = "companyName";
  @SerializedName(SERIALIZED_NAME_COMPANY_NAME)
  private String companyName;

  public static final String SERIALIZED_NAME_FILE_DESCRIPTION = "fileDescription";
  @SerializedName(SERIALIZED_NAME_FILE_DESCRIPTION)
  private String fileDescription;

  public WindowsMetadataAllOf() { 
  }

  public WindowsMetadataAllOf companyName(String companyName) {
    
    this.companyName = companyName;
    return this;
  }

   /**
   * The specified company name
   * @return companyName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Company Inc.", value = "The specified company name")

  public String getCompanyName() {
    return companyName;
  }


  public void setCompanyName(String companyName) {
    this.companyName = companyName;
  }


  public WindowsMetadataAllOf fileDescription(String fileDescription) {
    
    this.fileDescription = fileDescription;
    return this;
  }

   /**
   * The specified app description
   * @return fileDescription
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "MyApp: a free Windows app", value = "The specified app description")

  public String getFileDescription() {
    return fileDescription;
  }


  public void setFileDescription(String fileDescription) {
    this.fileDescription = fileDescription;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WindowsMetadataAllOf windowsMetadataAllOf = (WindowsMetadataAllOf) o;
    return Objects.equals(this.companyName, windowsMetadataAllOf.companyName) &&
        Objects.equals(this.fileDescription, windowsMetadataAllOf.fileDescription);
  }

  @Override
  public int hashCode() {
    return Objects.hash(companyName, fileDescription);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WindowsMetadataAllOf {\n");
    sb.append("    companyName: ").append(toIndentedString(companyName)).append("\n");
    sb.append("    fileDescription: ").append(toIndentedString(fileDescription)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

